services:
  stashr:
    image: larsmikki/stashr:latest
    container_name: stashr
    ports:
      - "3010:3010"
    volumes:
      - stash_data:/app/data
      - stash_cache:/app/cache
      # Replace with the path to your media folder: :ro=Read-only
      - /volume2/Private:/media:ro
    environment:
      - PORT=3010
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3010/api/health"]
      interval: 5m
      timeout: 10s
      retries: 3
    restart: always

volumes:
  stash_data:
  stash_cache:
